### ISSUE TITLE
Failing build on VSX with XL compiler

### ISSUE THREAD

**Issue by tasmith4** [kokkos/simd-math#25] opened 2020-12-08 14:53 UTC
Building stk_simd on vortex using the XL compiler yields several errors like this:

```
In file included from /vscratch1/tasmit/code/stk/stk_simd/stk_simd/kokkos_simd/simd.hpp:81:
/vscratch1/tasmit/code/stk/stk_simd/stk_simd/kokkos_simd/vsx.hpp:230:22: error: no matching function for call to 'vec_and'
return simd_mask(vec_and(m_value, other.m_value));
^~~~~~~
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2452:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector unsigned char' (vector of 16 'unsigned char' values) for 1st argument
vec_and(vector unsigned char __a, vector unsigned char __b) __asm__("__IBMBuiltin_vec_and_VUcVUcVUc");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2455:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector unsigned char' (vector of 16 'unsigned char' values) for 1st argument
vec_and(vector unsigned char __a, vector bool char __b) __asm__("__IBMBuiltin_vec_and_VUcVUcVBc");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2458:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector __bool unsigned char' (vector of 16 'unsigned char' values) for 1st argument
vec_and(vector bool char __a, vector unsigned char __b) __asm__("__IBMBuiltin_vec_and_VUcVBcVUc");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2461:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector signed char' (vector of 16 'signed char' values) for 1st argument
vec_and(vector signed char __a, vector signed char __b) __asm__("__IBMBuiltin_vec_and_VScVScVSc");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2464:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector signed char' (vector of 16 'signed char' values) for 1st argument
vec_and(vector signed char __a, vector bool char __b) __asm__("__IBMBuiltin_vec_and_VScVScVBc");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2467:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector __bool unsigned char' (vector of 16 'unsigned char' values) for 1st argument
vec_and(vector bool char __a, vector signed char __b) __asm__("__IBMBuiltin_vec_and_VScVBcVSc");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2470:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector __bool unsigned char' (vector of 16 'unsigned char' values) for 1st argument
vec_and(vector bool char __a, vector bool char __b) __asm__("__IBMBuiltin_vec_and_VBcVBcVBc");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2473:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector unsigned short' (vector of 8 'unsigned short' values) for 1st argument
vec_and(vector unsigned short __a, vector unsigned short __b) __asm__("__IBMBuiltin_vec_and_VUsVUsVUs");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2476:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector unsigned short' (vector of 8 'unsigned short' values) for 1st argument
vec_and(vector unsigned short __a, vector bool short __b) __asm__("__IBMBuiltin_vec_and_VUsVUsVBs");
^
/usr/tce/packages/xl/xl-2020.09.17/xlC/16.1.1/include/altivec.h:2479:1: note: candidate function not viable: no known conversion from 'const supported_type'
(vector of 2 'unsigned long' values) to '__vector __bool unsigned short' (vector of 8 'unsigned short' values) for 1st argument
vec_and(vector bool short __a, vector unsigned short __b) __asm__("__IBMBuiltin_vec_and_VUsVBsVUs");
^
```

My initial thought is that it is due to const issues, based on the following comment from [the GCC documentation](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/PowerPC-AltiVec_002fVSX-Built-in-Functions.html), which suggests our typical build with GCC automatically does the cast, but XL won't:

> GCC’s implementation of the high-level language interface available from C and C++ code differs from Motorola’s documentation in several ways.
>     ...
>     A vector initializer requires no cast if the vector constant is of the same type as the variable it is initializing.
>     ...

@ibaned can you reproduce?  Does this explanation make sense to you, and if so, what's your preferred path forward here?

FYI @alanw0

**Comment by ibaned** [comment] 2020-12-08 17:45
@tasmith4 can you follow up with an email to me letting me know which machine I can log onto to reproduce this?

It looks like the intrinsic `vec_and` is simply not available for the `unsigned long` type.

Personally, my preferred path forward is to drop support for the XL compiler.

Ironically, the main reason that vendors suggest their compiler is better than the open compilers is that it auto-vectorizes better, but thorough use of our `simd` types takes vectorization into our own hands and ensures our codes are well vectorized regardless of the compiler's auto-vectorization capability (better vectorized, in fact, because compilers are not capable of outer loop vectorization for complex kernels).

**Comment by alanw0** [comment] 2020-12-08 18:01
@ibaned Hi Dan, the machine is vortex.
We understand (from Mike Glass) that SPARC is the user here; they are using or trying to use, the XL compilers.
It's possible that a just-as-good solution would be to allow a macro that turns off intrinsics and just uses scalar. In stk-simd we have a macro USE_STK_SIMD_NONE. Would you be agreeable to a patch for kokkos-simd that allowed for a similar macro that would then bypass all instruction-set-specific stuff and just expose scalar?
By the way, we want to continue making stk-simd be as 'thin' as possible, with the ultimate goal of deferring completely to kokkos-simd.

**Comment by ibaned** [comment] 2020-12-08 19:33
Well, we may be able to come up with a different data type for the `simd_mask` on IBM CPUs... let me see if I can figure anything out on Vortex

**Comment by ibaned** [comment] 2020-12-08 19:53
@alanw0 @tasmith4 it turns out that the right type to use is not `vector bool long` or `vector bool unsigned long` but rather `vector bool long long`. I made this change in commit 2caf6be987c9b0addd39b9836864365aadf6727e and it seems to work with both XL and GCC compilers.

**Comment by tasmith4** [comment] 2020-12-08 19:55
Thanks!  We'll bring that fix into STK.

**Comment by ibaned** [comment] 2020-12-08 19:57
Closing as assumed fixed, please comment if this is still a problem.

**Closed by ibaned** 2020-12-08 19:57 UTC
